export const quizCategory = [
  {
    category_name: "Mathematics",
    quizzes: [
      {
        id: 1,
        quiz_name: "Triangles",
        instructor: "Ali Smith",
        score: 4.75,
        vote_count: 220,
        questionAmount: 10,
      },
      {
        id: 2,
        quiz_name: "Algebra",
        instructor: "Ayşe Johnson",
        score: 3.25,
        vote_count: 333,
        questionAmount: 10,
      },
      {
        id: 3,
        quiz_name: "Trigonometry",
        instructor: "Mehmet Kaya",
        score: 2.1,
        vote_count: 150,
        questionAmount: 10,
      },
      {
        id: 4,
        quiz_name: "Limits and Derivatives",
        instructor: "Fatma Yılmaz",
        score: 4.9,
        vote_count: 110,
        questionAmount: 10,
      },
    ],
  },
  {
    category_name: "History",
    quizzes: [
      {
        id: 1,
        quiz_name: "Ottoman Empire",
        instructor: "Mehmet Demir",
        score: 1.4,
        vote_count: 180,
        questionAmount: 10,
      },
      {
        id: 2,
        quiz_name: "Republic Era",
        instructor: "Fatma Çelik",
        score: 3.8,
        vote_count: 210,
        questionAmount: 10,
      },
      {
        id: 3,
        quiz_name: "World War II",
        instructor: "Zeynep Öztürk",
        score: 4.2,
        vote_count: 90,
        questionAmount: 10,
      },
      {
        id: 4,
        quiz_name: "Cold War",
        instructor: "Ahmet Şahin",
        score: 2.65,
        vote_count: 300,
        questionAmount: 10,
      },
    ],
  },
  {
    category_name: "Biology",
    quizzes: [
      {
        id: 1,
        quiz_name: "Cell Biology",
        instructor: "Zeynep Özdemir",
        score: 4.3,
        vote_count: 50,
        questionAmount: 10,
      },
      {
        id: 2,
        quiz_name: "Genetics",
        instructor: "Ahmet Karadeniz",
        score: 3.9,
        vote_count: 250,
        questionAmount: 10,
      },
      {
        id: 3,
        quiz_name: "Ecology",
        instructor: "Ayşe Aksoy",
        score: 4.15,
        vote_count: 175,
        questionAmount: 10,
      },
      {
        id: 4,
        quiz_name: "Classification of Organisms",
        instructor: "Mehmet Gür",
        score: 4.45,
        vote_count: 55,
        questionAmount: 10,
      },
    ],
  },
  {
    category_name: "English",
    quizzes: [
      {
        id: 1,
        quiz_name: "Grammar",
        instructor: "John Brown",
        score: 4.85,
        vote_count: 190,
        questionAmount: 10,
      },
      {
        id: 2,
        quiz_name: "Vocabulary",
        instructor: "Emma White",
        score: 3.6,
        vote_count: 49,
        questionAmount: 10,
      },
      {
        id: 3,
        quiz_name: "Reading Comprehension",
        instructor: "Michael Green",
        score: 4.4,
        vote_count: 220,
        questionAmount: 10,
      },
      {
        id: 4,
        quiz_name: "Writing Skills",
        instructor: "Sarah Davis",
        score: 4.75,
        vote_count: 194,
        questionAmount: 10,
      },
    ],
  },
];
