export const wholeQuizes = [
  {
    category_name: "Mathematics",
    quizzes: [
      {
        quiz_name: "Triangles",
        instructor: "Ali Smith",
        score: 4.75,
        vote_count: 220,
      },
      {
        quiz_name: "Algebra",
        instructor: "Ayşe Johnson",
        score: 3.25,
        vote_count: 333,
      },
      {
        quiz_name: "Trigonometry",
        instructor: "Mehmet Kaya",
        score: 2.1,
        vote_count: 150,
      },
      {
        quiz_name: "Limits and Derivatives",
        instructor: "Fatma Yılmaz",
        score: 4.9,
        vote_count: 110,
      },
      {
        quiz_name: "Calculus",
        instructor: "Emre Demir",
        score: 4.4,
        vote_count: 175,
      },
      {
        quiz_name: "Probability",
        instructor: "Ece Yıldız",
        score: 3.8,
        vote_count: 200,
      },
      {
        quiz_name: "Statistics",
        instructor: "Cemal Karakuş",
        score: 4.2,
        vote_count: 150,
      },
      {
        quiz_name: "Linear Algebra",
        instructor: "Selin Taş",
        score: 3.9,
        vote_count: 180,
      },
      {
        quiz_name: "Differential Equations",
        instructor: "Gözde Arslan",
        score: 4.6,
        vote_count: 250,
      },
      {
        quiz_name: "Number Theory",
        instructor: "Barış Öz",
        score: 3.5,
        vote_count: 120,
      },
      {
        quiz_name: "Geometry",
        instructor: "Berkay Korkmaz",
        score: 4.1,
        vote_count: 210,
      },
      {
        quiz_name: "Optimization",
        instructor: "Deniz Doğan",
        score: 4.8,
        vote_count: 300,
      },
      {
        quiz_name: "Complex Analysis",
        instructor: "Efe Şimşek",
        score: 3.7,
        vote_count: 90,
      },
      {
        quiz_name: "Mathematical Logic",
        instructor: "Nilgün Türk",
        score: 4.3,
        vote_count: 150,
      },
      {
        quiz_name: "Game Theory",
        instructor: "Can Çelik",
        score: 4.0,
        vote_count: 200,
      },
      {
        quiz_name: "Set Theory",
        instructor: "Sude Kaya",
        score: 4.5,
        vote_count: 180,
      },
    ],
  },
  {
    category_name: "History",
    quizzes: [
      {
        quiz_name: "Ancient Civilizations",
        instructor: "Murat Demir",
        score: 4.8,
        vote_count: 220,
      },
      {
        quiz_name: "Medieval Ages",
        instructor: "Ayşe Kaya",
        score: 4.2,
        vote_count: 333,
      },
      {
        quiz_name: "Renaissance Era",
        instructor: "Mehmet Öztürk",
        score: 3.5,
        vote_count: 150,
      },
      {
        quiz_name: "Colonial Period",
        instructor: "Fatma Yıldız",
        score: 4.5,
        vote_count: 110,
      },
      {
        quiz_name: "World War I",
        instructor: "Ali Çelik",
        score: 3.9,
        vote_count: 175,
      },
      {
        quiz_name: "Industrial Revolution",
        instructor: "Zeynep Karakuş",
        score: 4.1,
        vote_count: 200,
      },
      {
        quiz_name: "World War II",
        instructor: "Ahmet Yılmaz",
        score: 4.6,
        vote_count: 250,
      },
      {
        quiz_name: "Cold War",
        instructor: "Berkcan Korkmaz",
        score: 4.3,
        vote_count: 120,
      },
      {
        quiz_name: "Modern Era",
        instructor: "Can Doğan",
        score: 4.9,
        vote_count: 210,
      },
      {
        quiz_name: "Contemporary Issues",
        instructor: "Selin Demir",
        score: 4.4,
        vote_count: 300,
      },
      {
        quiz_name: "Historical Figures",
        instructor: "Nilgün Çelik",
        score: 3.7,
        vote_count: 90,
      },
      {
        quiz_name: "Revolutionary Movements",
        instructor: "Efe Arslan",
        score: 4.0,
        vote_count: 150,
      },
      {
        quiz_name: "Cultural History",
        instructor: "Deniz Kaya",
        score: 4.7,
        vote_count: 200,
      },
      {
        quiz_name: "History of Art",
        instructor: "Sude Taş",
        score: 3.6,
        vote_count: 180,
      },
      {
        quiz_name: "Political History",
        instructor: "Barış Demir",
        score: 4.2,
        vote_count: 220,
      },
      {
        quiz_name: "Social Movements",
        instructor: "Ege Yılmaz",
        score: 4.5,
        vote_count: 180,
      },
    ],
  },
  {
    category_name: "Biology",
    quizzes: [
      {
        quiz_name: "Cell Biology",
        instructor: "Zeynep Özdemir",
        score: 4.3,
        vote_count: 220,
      },
      {
        quiz_name: "Genetics",
        instructor: "Ahmet Karadeniz",
        score: 3.9,
        vote_count: 333,
      },
      {
        quiz_name: "Ecology",
        instructor: "Ayşe Aksoy",
        score: 4.0,
        vote_count: 150,
      },
      {
        quiz_name: "Classification of Organisms",
        instructor: "Mehmet Gür",
        score: 4.5,
        vote_count: 110,
      },
      {
        quiz_name: "Biochemistry",
        instructor: "Fatma Yıldız",
        score: 4.8,
        vote_count: 175,
      },
      {
        quiz_name: "Microbiology",
        instructor: "Ali Çelik",
        score: 4.2,
        vote_count: 200,
      },
      {
        quiz_name: "Evolutionary Biology",
        instructor: "Zeynep Karakuş",
        score: 4.6,
        vote_count: 250,
      },
      {
        quiz_name: "Physiology",
        instructor: "Berkcan Korkmaz",
        score: 4.4,
        vote_count: 120,
      },
      {
        quiz_name: "Botany",
        instructor: "Can Doğan",
        score: 4.9,
        vote_count: 210,
      },
      {
        quiz_name: "Zoology",
        instructor: "Selin Demir",
        score: 4.7,
        vote_count: 300,
      },
      {
        quiz_name: "Immunology",
        instructor: "Nilgün Çelik",
        score: 4.1,
        vote_count: 90,
      },
      {
        quiz_name: "Neuroscience",
        instructor: "Efe Arslan",
        score: 4.2,
        vote_count: 150,
      },
      {
        quiz_name: "Biotechnology",
        instructor: "Deniz Kaya",
        score: 4.5,
        vote_count: 200,
      },
      {
        quiz_name: "Bioinformatics",
        instructor: "Sude Taş",
        score: 3.8,
        vote_count: 180,
      },
      {
        quiz_name: "Marine Biology",
        instructor: "Barış Demir",
        score: 4.0,
        vote_count: 220,
      },
      {
        quiz_name: "Ecological Genetics",
        instructor: "Ege Yılmaz",
        score: 4.3,
        vote_count: 180,
      },
    ],
  },
  {
    category_name: "English",
    quizzes: [
      {
        quiz_name: "Grammar",
        instructor: "John Brown",
        score: 4.9,
        vote_count: 220,
      },
      {
        quiz_name: "Vocabulary",
        instructor: "Emma White",
        score: 3.2,
        vote_count: 333,
      },
      {
        quiz_name: "Reading Comprehension",
        instructor: "Michael Green",
        score: 4.2,
        vote_count: 150,
      },
      {
        quiz_name: "Writing Skills",
        instructor: "Sarah Davis",
        score: 4.7,
        vote_count: 110,
      },
      {
        quiz_name: "Listening Skills",
        instructor: "James Smith",
        score: 4.8,
        vote_count: 175,
      },
      {
        quiz_name: "Speaking Fluency",
        instructor: "Olivia Johnson",
        score: 4.5,
        vote_count: 200,
      },
      {
        quiz_name: "Pronunciation",
        instructor: "William Miller",
        score: 4.6,
        vote_count: 250,
      },
      {
        quiz_name: "Writing Essays",
        instructor: "Ava Wilson",
        score: 4.4,
        vote_count: 120,
      },
      {
        quiz_name: "Literature Analysis",
        instructor: "Noah Anderson",
        score: 4.3,
        vote_count: 210,
      },
      {
        quiz_name: "Creative Writing",
        instructor: "Sophia Martinez",
        score: 4.5,
        vote_count: 300,
      },
      {
        quiz_name: "Public Speaking",
        instructor: "Ethan Thompson",
        score: 4.1,
        vote_count: 90,
      },
      {
        quiz_name: "Debate Skills",
        instructor: "Isabella Garcia",
        score: 4.0,
        vote_count: 150,
      },
      {
        quiz_name: "English Literature",
        instructor: "Daniel Harris",
        score: 4.7,
        vote_count: 200,
      },
      {
        quiz_name: "TOEFL Preparation",
        instructor: "Liam Clark",
        score: 4.5,
        vote_count: 180,
      },
      {
        quiz_name: "IELTS Preparation",
        instructor: "Sophie Lewis",
        score: 4.6,
        vote_count: 220,
      },
      {
        quiz_name: "Business English",
        instructor: "Mia King",
        score: 4.3,
        vote_count: 180,
      },
    ],
  },
];
